# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to your about:config while the program is running, the changes will be overwritten when the application restarts.
 * To make a manual change to preferences, you will have to manually edit the user.js file.
 *
 * Should any issue arise, assuming it's on an https site, try disabling "security.ssl.treat_unsafe_negotiation_as_broken."
 */

user_pref("Network.cookie.p3p", "frfrarar");
user_pref("app.update.url", "");
user_pref("app.update.url.details", "");
user_pref("app.update.url.manual", "");
user_pref("beacon.enabled", false);
user_pref("browser.newtabpage.directory.ping", "");
user_pref("browser.newtab.preload", false);
user_pref("browser.pagethumbnails.capturing_disabled", true);
user_pref("browser.safebrowsing.appRepURL", "");
user_pref("browser.safebrowsing.downloads.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.updateURL", "");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.geoSpecificDefaults", false);
user_pref("browser.search.geoip.url", "");
user_pref("browser.search.hiddenOneOffs", "");
user_pref("browser.search.region", "US");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.search.update", false);
user_pref("browser.selfsupport.url", "");
user_pref("browser.send_pings", false);
user_pref("browser.send_pings.require_same_host", true); //if you rely on the above pref
user_pref("browser.sessionstore.privacy_level_deferred", 2);
user_pref("browser.tabs.onTop", false);
user_pref("datareporting.healthreport.service.firstRun", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("dom.battery.enabled", false);
user_pref("dom.enable_performance", false);
user_pref("dom.event.clipboardevents.enabled", false);
user_pref("dom.event.contextmenu.enabled", false);
user_pref("dom.gamepad.enabled", false);
user_pref("dom.ipc.plugins.flash.subprocess.crashreporter.enabled", false);
user_pref("dom.mozApps.used", true);
user_pref("dom.storage.default_quota", 1024);
user_pref("dom.webcomponents.enabled", true);
user_pref("experiments.enabled", false);
user_pref("experiments.supported", false);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("general.warnOnAboutConfig", false);
user_pref("general.useragent.locale", "en-us");
user_pref("geo.enabled", false);
user_pref("geo.wifi.uri", "");
user_pref("gfx.font_rendering.fallback.always_use_cmaps", true);
user_pref("gfx.use_text_smoothing_setting", true);
user_pref("intl.accept_languages", "en-us,en");
user_pref("keyword.enabled", false);
/* Youtube crap */
user_pref("media.fragmented-mp4.ffmpeg.enabled", true);
user_pref("media.fragmented-mp4.gmp.enabled", true);
user_pref("media.getusermedia.screensharing.enabled", false);
user_pref("media.mediasource.ignore_codecs", true);
user_pref("media.mediasource.webm.enabled", true);
/* Youtube crap ends here */
user_pref("media.navigator.enabled", false);
user_pref("media.peerconnection.enabled", false);
user_pref("media.webspeech.recognition.enable", false);
user_pref("network.accept-encoding", "gzip, deflate");
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.cookie.lifetime.days", 1);
user_pref("network.cookie.lifetimePolicy", 3);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
/* Pipelining crap */
user_pref("network.http.pipelining", true);
user_pref("network.http.pipelining.aggressive", true);
user_pref("network.http.pipelining.max-optimistic-requests", 8);
user_pref("network.http.pipelining.ssl", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.http.proxy.pipelining", true);
/* Pipelining crap ends here */
user_pref("network.http.referer.spoofSource", true);
user_pref("network.http.sendSecureXSiteReferrer", false);
user_pref("network.IDN_show_punycode", true);
user_pref("network.negotiate-auth.allow-insecure-ntlm-v1", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugins.enumerable_names", "");
user_pref("plugins.hide_infobar_for_outdated_plugin", false);
user_pref("plugins.update.notifyUser", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.csp.experimentalEnabled", true);
user_pref("security.mixed_content.block_display_content", true);
user_pref("security.cert_pinning.enforcement_level", 2);
user_pref("security.ssl.errorReporting.enabled", false);
user_pref("security.ssl.treat_unsafe_negotiation_as_broken", true);
user_pref("security.ssl3.ecdhe_ecdsa_rc4_128_sha", false);
user_pref("security.ssl3.ecdhe_rsa_rc4_128_sha", false);
user_pref("security.ssl3.rsa_rc4_128_md5", false);
user_pref("security.ssl3.rsa_rc4_128_sha", false);
user_pref("security.xpconnect.plugin.unrestricted", false);
user_pref("security.warn_entering_weak", true);
user_pref("security.warn_viewing_mixed", true);
user_pref("services.sync.prefs.sync.browser.safebrowsing.enabled", false);
user_pref("services.sync.prefs.sync.browser.safebrowsing.malware.enabled", false);
user_pref("ui.mouse.radius.inputSource.touchOnly", false);
user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20100101 Firefox/31.0");
